#!/usr/bin/env python
import subprocess
print("GIVE YOUR INTERFACE")
interface=input()
print("GIVE NEW MAC AS YOU WANT")
new_mac=input()
subprocess.call("ifconfig "+interface+" down",shell=True)
subprocess.call("ifconfig "+interface+" hw ether "+ new_mac,shell=True)
subprocess.call("ifconfig wlan0 up",shell=True)
